### ISSUE TITLE
1.4.6: internal poll failure reading response from client B.Schaffl to a latency callback event

### ISSUE THREAD

**Issue by yurivict** [sjaehn/BSchaffl#17] opened 2021-04-07 00:33 UTC
Please see the screenshot video:

https://user-images.githubusercontent.com/271906/113793884-33367a80-96fe-11eb-9849-a96cff3081ac.mp4

**Comment by sjaehn** [comment] 2021-04-07 12:01
I can't reproduce it on Ubuntu 20.04. It looks like your system doesn't like any live change in latency. But then, the host behaviour is odd.

I'm a bit surprised about calling jalv with `sudo`. And I also wonder where the error messages come from. Jalv or jackd? I've got jackd2 (1.9.12) running without any problems.

**Comment by yurivict** [comment] 2021-04-07 16:31
> I'm a bit surprised about calling jalv with sudo

This was just to make sure permissions aren't a problem. It runs fine without sudo.

> And I also wonder where the error messages come from. Jalv or jackd? I've got jackd2 (1.9.12) running without any problems.

jackd2 doesn't yet run on FreeBSD. People are working on making it compatible.

**Comment by sjaehn** [comment] 2021-04-07 17:16
> It runs fine without sudo.

Do you mean "it runs in the same way" (I guess you mean this) or do you mean "it runs without any errors" ? And do you see the same problem with other hosts (like Carla, Ardour, ...)?

I think it has something to do with jalv and the jack/jack2 problem. And it is somehow related to https://github.com/sjaehn/BChoppr/issues/12. The error messages look like jack.

The only maybe "evil" thing that B.Schaffl does is dynamicly changing the latency *value* by re-calculating https://github.com/sjaehn/BSchaffl/blob/cf507ccb6c733e7acb24886d359a244f348ba703/src/BSchaffl.cpp#L935 and writing to the LV2 latency output port https://github.com/sjaehn/BSchaffl/blob/cf507ccb6c733e7acb24886d359a244f348ba703/src/BSchaffl.cpp#L137 which is defined there: https://github.com/sjaehn/BSchaffl/blob/cf507ccb6c733e7acb24886d359a244f348ba703/BSchaffl.ttl#L729-L737 That's all for the plugin. It doesn't do anything else with latency. And it doesn't have got any direct access to jack.

It's the hosts task to handle the latency value reported by the plugin. Maybe @drobilla (who made jalv and the most of the LV2 tools) knows a bit more.

**Comment by drobilla** [comment] 2021-04-08 17:08
No idea, sorry, I'd have to look in to it.  Jalv does attempt to report changed latency to JACK.  I have no idea off the top of my head whether how/when/etc it does so is correct, though.  Maybe @x42 who originally wrote that code and generally understands JACK latency far better will have some idea.

**Comment by x42** [comment] 2021-04-08 17:31
Last I check (3-4 years ago)  jalv did not notify jack when the plugin's latency changes.
However. changing jack port connections triggers a latency-callback, and jalv will use the current value.
check with `jack_lsp -l`

**Comment by drobilla** [comment] 2021-04-08 18:00
https://github.com/drobilla/jalv/commit/cebeaf23baa346201e76658139caa68d7d33d42f

**Comment by x42** [comment] 2021-04-08 18:51
@drobilla  so the patch calls `jack_recompute_total_latencies()`  whenever the plugin's latency changes from the process-callback.  -- No idea if that works with jack1, ask some JACK threading expert.

The rest of the code reads fine.

**Comment by pauldavisthefirst** [comment] 2021-04-08 18:54
jack_recompute_total_latencies() is a server call. It is not legal to make server calls from within a server callback (like the process callback).

**Comment by sjaehn** [comment] 2021-04-09 21:17
I'm closing this issue here as it looks like a host-related problem and @drobilla  already opened an issue there: https://github.com/drobilla/jalv/issues/49.

**Closed as completed by sjaehn** 2021-04-09 21:17 UTC
