### ISSUE TITLE
Unwanted midi changes.

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BSchaffl#2] opened 2020-06-07 15:26 UTC
Wow, you got that done incredibly quick!
It looks great, and seems to have all the important functionality.

Except, on my system, it doesn't work yet. :(
When I input a straight 16th note pattern, and leave all the controls at default, I get a sort of shuffle out, with lots of dropped notes.

Attached is an Ardour 6 test session.
Does that work for you?

[BSchaffl_test.zip](https://github.com/sjaehn/BSchaffl/files/4742335/BSchaffl_test.zip)

**Comment by sjaehn** [comment] 2020-06-07 16:08
I can reproduce this problem with Ardour 5.12. It looks like the same problem as described by myself in issue #1 . If the NOTE_OFF for the first note is scheduled shortly *after* the NOTE_ON for the second note and both notes have the same pitch you will hear (almost) nothing (= "dropped notes"). This shouldn't happen if the notes have different pitches. 

I will do a dump to confirm it. If this overlap comes from the input, a "smart quantization" algorithm (see README.md#TODO's) should fix it. If it only appears on the output side (I'm afraid) then it's a bug.

**Comment by sjaehn** [comment] 2020-06-07 17:01
It was a bug. Fixed in f5cf02685dd2f21d1ce918285577e5cf0c1609f5 . Also added MIDI scheduler dump to stderr.

**Comment by magnetophon** [comment] 2020-06-08 07:57
That's better; with the default settings, it bypasses.
When I change the swing slider I get a swing pattern, but also periods of silence, and sometimes I need to start and stop Ardour to get sound back.

**Comment by sjaehn** [comment] 2020-06-08 10:32
> That's better; with the default settings, it bypasses.

What do you mean with "bypasses"? You should hear the origial 1/16 note pattern. If you don't hear anything or if you hear something else then it's a bug.

> When I change the swing slider I get a swing pattern, but also periods of silence...

I'll try to reproduce it.

**Comment by magnetophon** [comment] 2020-06-08 10:35
> What do you mean with "bypasses"?

Sorry, that was unclear.  Yes, it passes trough the midi unchanged, as it should.

**Comment by sjaehn** [comment] 2020-06-08 17:38
Thanks  for reporting. After a while of playing around I observed a similar (or the same?) bug and I analyzed the dump. I found "old" (from a stopped previous run) midi messages sticking in front of the midi event queue and these messages block all new messages. I will look how to fix it.

**Comment by sjaehn** [comment] 2020-06-08 18:29
Quick fix in 94ad289cfdaefdf5cab56d07962dbf72466c40a1 . This fix will kill all "old" scheduled midi messages from the queue. I hope this will fix the problem you described.

For the future I have look for a smarter solution. Otherwise other ideas, like MIDI filtering and smart quantization (fitting NOTE_OFF to the end of a step and NOTE_ON to the start of a step) will not work.

**Comment by magnetophon** [comment] 2020-06-08 18:52
Yes, it works!
This thing is even more fun to play with then I imagined when I asked for it.
Thank you so much!

It indeed look like you need to look for a smarter solution, as there are some timing bugs remaining.
For example the first bar of a song plays unchanged for me.

**Comment by sjaehn** [comment] 2020-06-09 21:24
You reported the "first bar bug" to be solved in https://github.com/sjaehn/BSchaffl/issues/3 . Thanks.

Smart quantization is now introduced in c2eec870b601ad6d94494512e06971db5a56155d . This means that NOTE_ON signals can now be mapped to (the amp of) the just starting step whereas NOTE_OFF signal can be mapped to the ending step by definition of a range. The edge problem is solved.

Still TODO: classic quantization (re-positioning of not exactly placed MIDI signals.

**Closed as completed** 2020-06-11 20:44 UTC
Labels: bug
